Merge meta data in setup.cfg into pyproject.toml
neutrons/LiquidsReflectometer pull request #34
Opened 2024-07-19 20:17 UTC by KyleQianliMa

# Short description of the changes:

Merging meta data in setup.cfg into pyproject.toml.
This is to address [Story 3163](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=3163)
# Long description of the changes:

# Check list for the pull request
- [ ] I have read the [CONTRIBUTING]
- [ ] I have read the [CODE_OF_CONDUCT]
- [ ] I have added tests for my changes
- [ ] I have updated the documentation accordingly

# Check list for the reviewer
- [ ] I have read the [CONTRIBUTING]
- [ ] I have verified the proposed changes
- [ ] best software practices
    + [ ] all internal functions have an underbar, as is python standard
    + [ ] clearly named variables (better to be verbose in variable names)
    + [ ] code comments explaining the intent of code blocks
- [ ] All the tests are passing
- [ ] The documentation is up to date
- [ ] code comments added when explaining intent

# Manual test for the reviewer

# References

2024-07-19 22:45 UTC, jmborr requested changes
did you try installing the package with `pip install -e .`?

2024-07-19 22:45 UTC, jmborr commented on pyproject.toml
> +dynamic = ["version"]
```suggestion
version = "0.1.0"  # initial version, dynamically overriden
```

2024-07-19 22:45 UTC, jmborr commented on pyproject.toml
> +	{name = "Mat", email = "m2d@ornl.gov"}
change tab to spaces

2024-07-19 22:45 UTC, jmborr commented on pyproject.toml
> +
remove the empty line

2024-07-19 22:45 UTC, jmborr commented on pyproject.toml
>  ]
"Topic :: Scientific/Engineering :: Neutron reflectometry"

2024-07-19 22:45 UTC, jmborr commented on pyproject.toml
> +    "typing"
remove `typing`, `mock`, and `pytest-qt`

2024-07-23 14:57 UTC, KyleQianliMa commented
added 
[tool.setuptools.packages.find]
where = ["reduction"]
exclude = ["tests*", "scripts*", "docs*", "notebooks*"] in pyproject.toml and addressed other comments.

2024-07-23 23:12 UTC, jmborr approved these changes

2024-07-24 14:39 UTC, KyleQianliMa commented
I think the conflict has been resolved and now ready to merge

2024-07-24 16:29 UTC, jmborr approved these changes
`pip install -e .` now installs package `lr_reduction` so that later one can do `import lr_reduction`.

2024-07-24 17:11 UTC, merged